'use strict';
/**
 * 14단계 C: 낚시 + 별자리 + 도감.
 *  - 단위: 낚시 규칙(10종·확률·세션 타이밍) · 별자리 365개(유일·좌표·날짜 인덱스·밤 판정) · 메모리 저장소(fish_catches 집계/오늘 tz · constellation_views · room_pets.tank) ·
 *    OutdoorWorld(cast/bite/reel/early/miss/moved/하루 5마리) · viewSky(밤/낮·첫 관측) · codex · 스터디 어항(setTank 규칙 · FishNpc 스냅샷 · 재시작 로드).
 *  - 소켓 E2E: playerFishing 방송 · fish:caught + 채팅(희귀는 전체) · sky:view · codex(야외에서 소속 스터디 어항) · fish:tank → 스터디 안 npc:update.
 *  - 브라우저: 낚싯대·"!"·물고기 아이콘 · 별자리 오버레이 캔버스 · 도감 탭.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const { getOutdoor } = require('../server/rooms/outdoor');
const { getStudyRoom } = require('../server/rooms/studyroom');
const { canStand } = require('../server/game/movement');
const { OutdoorWorld } = require('../server/game/outdoor');
const { World, TANK_MAX } = require('../server/game/world');
const Fishing = require('../server/game/fishing');
const Sky = require('../server/game/constellations');
const { createMemoryStore } = require('../server/store/memory');
const { boot, connect, joinAs, ask, once, sleep, collect, CHROME, CHROME_ARGS } = require('./helpers');

const T = 32;
const KST = (iso) => new Date(`${iso}+09:00`).getTime();
const outdoor = getOutdoor();
const quiet = { log() {}, warn() {}, error() {} };

function seeded(seed = 7) {
  let s = seed;
  return () => { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; };
}

function makeOutdoor(opts = {}) {
  let t = KST('2026-09-18T14:00:00');
  const store = opts.store || createMemoryStore();
  const world = new OutdoorWorld(outdoor, { now: () => t, store, tz: 'Asia/Seoul', npc: { autoStart: false, random: seeded(3), tickMs: 150 }, study: { autoTick: false }, log: quiet, ...opts });
  const advance = (ms) => { t += ms; };
  const settle = async () => { await Promise.all([...world.pendingAwards]); };
  return { world, store, advance, settle, now: () => t };
}

test('낚시 규칙: 10종(흔함 6·보통 3·희귀 1) · roll 확률 66/30/4 · 세션(5~10초 입질 → 1.2초 창) · 낚시 자리 4곳·망원경 지점', () => {
  assert.equal(Fishing.FISH.length, 10);
  assert.deepEqual(['common', 'uncommon', 'rare'].map((r) => Fishing.FISH.filter((f) => f.rarity === r).length), [6, 3, 1]);
  assert.equal(new Set(Fishing.FISH.map((f) => f.id)).size, 10);
  const cnt = { common: 0, uncommon: 0, rare: 0 };
  const r = seeded(99);
  for (let i = 0; i < 50000; i++) cnt[Fishing.roll(r).rarity]++;
  assert.ok(Math.abs(cnt.common / 50000 - 0.66) < 0.02 && Math.abs(cnt.uncommon / 50000 - 0.30) < 0.02 && Math.abs(cnt.rare / 50000 - 0.04) < 0.01, JSON.stringify(cnt));
  assert.equal(Fishing.roll(() => 0.999).id, 'golden_carp');
  assert.equal(Fishing.roll(() => 0).id, 'crucian');
  const s = Fishing.newSession('0', 1000, () => 0.5);
  assert.equal(s.biteAt, 1000 + Fishing.BITE_MIN_MS + Math.floor(0.5 * (Fishing.BITE_MAX_MS - Fishing.BITE_MIN_MS)));
  assert.equal(Fishing.tickSession(s, s.biteAt - 1), null);
  assert.equal(Fishing.reelOk(s, s.biteAt - 1), false, '입질 전 E 는 실패');
  assert.equal(Fishing.tickSession(s, s.biteAt), 'bite');
  assert.equal(Fishing.reelOk(s, s.biteAt + 500), true);
  assert.equal(Fishing.tickSession(s, s.biteAt + Fishing.REEL_WINDOW_MS + 1), 'miss');
  assert.equal(Fishing.reelOk(s, s.biteAt + 500), false, '창이 지나면 실패');
  assert.equal(outdoor.interactables.filter((i) => i.kind === 'fish').length, 4);
  for (const f of outdoor.interactables.filter((i) => i.kind === 'fish')) assert.ok(canStand(outdoor, f.x, f.y), '낚시 자리는 설 수 있다');
  const tel = outdoor.interactables.find((i) => i.kind === 'telescope');
  assert.ok(tel && canStand(outdoor, tel.x, tel.y));
});

test('별자리: 365개(이름·id 유일, 실제 88 + 상상 277) · 별 좌표 0..1 · 날짜 인덱스(tz 기준 그 해 몇 번째 날) · 밤 19~06시 판정', () => {
  assert.equal(Sky.LIST.length, 365);
  assert.equal(new Set(Sky.LIST.map((c) => c.name)).size, 365);
  assert.equal(new Set(Sky.LIST.map((c) => c.id)).size, 365);
  assert.equal(Sky.LIST.filter((c) => c.real).length, 88);
  for (const c of Sky.LIST) {
    assert.ok(c.name && c.desc && c.stars.length >= 4 && c.lines.length >= 2, c.id);
    for (const [x, y] of c.stars) assert.ok(x >= 0 && x <= 1 && y >= 0 && y <= 1);
    for (const [a, b] of c.lines) assert.ok(a < c.stars.length && b < c.stars.length);
  }
  assert.equal(Sky.dayOfYear(KST('2026-01-01T00:30:00'), 'Asia/Seoul'), 1);
  assert.equal(Sky.dayOfYear(KST('2026-12-31T23:00:00'), 'Asia/Seoul'), 365);
  assert.equal(Sky.indexFor(KST('2026-01-01T03:00:00'), 'Asia/Seoul'), 0);
  assert.equal(Sky.indexFor(KST('2026-09-18T12:00:00'), 'Asia/Seoul'), 260);
  assert.equal(Sky.indexFor(KST('2027-01-01T03:00:00'), 'Asia/Seoul'), 0, '해가 바뀌면 다시 처음');
  assert.notEqual(Sky.todays(KST('2026-09-18T12:00:00'), 'Asia/Seoul').id, Sky.todays(KST('2026-09-19T12:00:00'), 'Asia/Seoul').id);
  assert.equal(Sky.isNight(KST('2026-09-18T19:00:00'), 'Asia/Seoul'), true);
  assert.equal(Sky.isNight(KST('2026-09-18T05:59:00'), 'Asia/Seoul'), true);
  assert.equal(Sky.isNight(KST('2026-09-18T06:00:00'), 'Asia/Seoul'), false);
  assert.equal(Sky.isNight(KST('2026-09-18T18:59:00'), 'Asia/Seoul'), false);
  assert.ok(Sky.byId('UMa') && Sky.byId('UMa').name === '큰곰자리' && Sky.byId('UMa').stars.length === 8);
});

test('메모리 저장소 14단계: fish_catches(도감 집계·오늘 마릿수 tz) · constellation_views(첫 관측만) · room_pets.tank', async () => {
  const store = createMemoryStore();
  const t0 = KST('2026-09-18T23:30:00');
  await store.addFishCatch({ nickname: '민수', fishId: 'carp' }, t0);
  await store.addFishCatch({ nickname: '민수', fishId: 'carp' }, t0 + 1000);
  await store.addFishCatch({ nickname: '민수', fishId: 'koi' }, t0 + 2000);
  await store.addFishCatch({ nickname: '영희', fishId: 'carp' }, t0);
  const codex = await store.fishCodex('민수');
  assert.deepEqual(codex.map((r) => [r.fishId, r.count, r.firstAt]).sort(), [['carp', 2, t0], ['koi', 1, t0 + 2000]]);
  assert.equal(await store.fishCatchesToday('민수', { tz: 'Asia/Seoul', now: t0 + 3000 }), 3);
  assert.equal(await store.fishCatchesToday('민수', { tz: 'Asia/Seoul', now: t0 + 3600 * 1000 }), 0, '자정(KST)이 지나면 0');
  assert.equal(await store.fishCatchesToday('영희', { tz: 'Asia/Seoul', now: t0 }), 1);
  assert.deepEqual(await store.addConstellationView('민수', 'UMa', t0), { inserted: true, seenAt: t0 });
  assert.deepEqual(await store.addConstellationView('민수', 'UMa', t0 + 5000), { inserted: false, seenAt: t0 });
  await store.addConstellationView('민수', 'x001', t0 + 1);
  assert.deepEqual(await store.constellationViews('민수'), [{ constId: 'UMa', seenAt: t0 }, { constId: 'x001', seenAt: t0 + 1 }]);
  assert.deepEqual(await store.constellationViews('영희'), []);
  // 어항 (room_pets.tank)
  await store.adjustCoins('민수', 100, 'test');
  const sw = new World(getStudyRoom(), { now: () => t0, store, tz: 'Asia/Seoul', npc: { autoStart: false }, study: { autoTick: false }, log: quiet, studyId: 3 });
  await sw.init();
  const q = sw.join({ nickname: '민수', socketId: 's0' }).player;
  const bought = await sw.purchase(q, 'shared_fish');
  const rel = await sw.releasePet(q, { inventoryId: bought.inventory.id, name: '물방울' });
  assert.equal(rel.ok, true);
  assert.deepEqual(await store.setPetTank(rel.roomPetId, [{ fishId: 'carp', by: '민수', at: t0 }]), [{ fishId: 'carp', by: '민수', at: t0 }]);
  assert.deepEqual((await store.roomPets(3)).find((r) => r.id === rel.roomPetId).tank, [{ fishId: 'carp', by: '민수', at: t0 }]);
  assert.equal(await store.setPetTank(99999, []), null);
  await sw.dispose();
});

test('OutdoorWorld 낚시: 자리 앞에서 cast → wait → 입질(bite) → 창 안 reel 성공(저장·이벤트) · 이르면 early · 늦으면 miss · 움직이면 취소 · 하루 5마리 limit · 탑승 불가 · 퇴장 정리', async () => {
  const { world, store, advance, now, settle } = makeOutdoor({ npc: { autoStart: false, random: seeded(42), tickMs: 150 } });
  const p = world.join({ nickname: '민수', socketId: 's1' }).player;
  const ev = [];
  world.on('fishing', (e) => ev.push([e.state, e.result ? (e.result.ok ? 'ok' : e.result.reason) : null]));
  world.on('fishCaught', (e) => ev.push(['caught', e.fish.id, e.rare]));
  const spot = world.room.interactables.find((i) => i.id === 'fish:2');
  assert.equal((await world.cast(p, 9)).error, 'no_spot');
  assert.equal((await world.cast(p, 2)).error, 'too_far');
  p.x = spot.x; p.y = spot.y;
  p.vehicle = { type: 'kart' };
  assert.equal((await world.cast(p, 2)).error, 'riding');
  p.vehicle = null;
  const c1 = await world.cast(p, 2);
  assert.equal(c1.ok, true);
  assert.equal(c1.state, 'wait');
  assert.ok(c1.biteIn >= Fishing.BITE_MIN_MS && c1.biteIn <= Fishing.BITE_MAX_MS);
  assert.deepEqual(world.publicPlayer(p).fishing, { state: 'wait', spot: '2' });
  assert.equal((await world.cast(p, 2)).error, 'already');
  assert.equal((await world.reel(p)).error, 'early');
  assert.equal(world.publicPlayer(p).fishing, null);
  await world.cast(p, 2);
  const s = world.fishing.get(p.id);
  advance(s.biteAt - now() - 1);
  world.tickFishing(now());
  assert.equal(p.fishing.state, 'wait');
  advance(1);
  world.tickFishing(now());
  assert.equal(p.fishing.state, 'bite');
  advance(300);
  const r = await world.reel(p);
  assert.equal(r.ok, true);
  assert.ok(Fishing.fishById(r.fish.id));
  assert.equal(r.left, 4);
  assert.equal((await store.fishCodex('민수')).length, 1);
  await world.cast(p, 2);
  const s2 = world.fishing.get(p.id);
  advance(s2.windowUntil - now() + 1);
  world.tickFishing(now());
  assert.equal(p.fishing, null);
  assert.equal((await world.reel(p)).error, 'not_fishing');
  await world.cast(p, 2);
  p.budget = 10000; p.lastMoveAt = now() - 50;
  advance(100);
  assert.equal(world.move(p, { x: p.x + 20, y: p.y, facing: 'right', moving: true }).ok, true);
  assert.equal(p.fishing, null);
  assert.ok(ev.some((e) => e[1] === 'moved'));
  p.x = spot.x; p.y = spot.y;
  for (let i = 0; i < 4; i++) {
    assert.equal((await world.cast(p, 2)).ok, true);
    const ss = world.fishing.get(p.id);
    advance(ss.biteAt - now() + 100);
    world.tickFishing(now());
    assert.equal((await world.reel(p)).ok, true);
  }
  assert.equal((await world.cast(p, 2)).error, 'limit');
  assert.equal(await store.fishCatchesToday('민수', { tz: 'Asia/Seoul', now: now() }), 5);
  advance(24 * 3600 * 1000);
  assert.equal((await world.cast(p, 2)).ok, true, '다음 날 다시');
  world.endFishing(p);
  assert.equal(ev.filter((e) => e[0] === 'caught').length, 5);
  assert.deepEqual(ev.slice(0, 2), [['wait', null], [null, 'early']]);
  await world.cast(p, 2);
  world.detach(p, 'outdoor');
  assert.equal(world.fishing.size, 0);
  await settle();
  await world.dispose();
});

test('OutdoorWorld 별자리·도감: 망원경 앞 + 밤(tz)에만 viewSky(오늘의 별자리·첫 관측 first) · 낮엔 daytime · codex · 스터디 어항(setTank 규칙·FishNpc 스냅샷·재시작 로드)', async () => {
  let t = KST('2026-09-18T22:00:00');
  const store = createMemoryStore();
  const world = new OutdoorWorld(outdoor, { now: () => t, store, tz: 'Asia/Seoul', npc: { autoStart: false, random: seeded(3), tickMs: 150 }, study: { autoTick: false }, log: quiet });
  const p = world.join({ nickname: '민수', socketId: 's1' }).player;
  assert.equal((await world.viewSky(p)).error, 'too_far');
  const tel = world.room.interactables.find((i) => i.id === 'telescope');
  p.x = tel.x; p.y = tel.y;
  const v = await world.viewSky(p);
  assert.equal(v.ok, true);
  assert.equal(v.index, 260);
  assert.equal(v.constellation.id, Sky.todays(t, 'Asia/Seoul').id);
  assert.equal(v.first, true);
  assert.ok(Array.isArray(v.constellation.stars) && v.constellation.lines.length);
  assert.equal((await world.viewSky(p)).first, false);
  t = KST('2026-09-18T12:00:00');
  const d = await world.viewSky(p);
  assert.equal(d.error, 'daytime');
  assert.equal(d.hour, 12);
  t = KST('2026-09-19T05:30:00');
  assert.equal((await world.viewSky(p)).ok, true, '새벽 5시 반은 밤');
  assert.equal((await world.viewSky(p)).constellation.id, Sky.todays(t, 'Asia/Seoul').id, '날짜가 바뀌면 다음 별자리');
  await store.addFishCatch({ nickname: '민수', fishId: 'koi' }, t - 1000);
  const codex = await world.codex(p);
  assert.equal(codex.ok, true);
  assert.equal(codex.fish.length, 10);
  assert.equal(codex.fish.find((f) => f.id === 'koi').count, 1);
  assert.equal(codex.fish.find((f) => f.id === 'carp').count, 0);
  assert.equal(codex.caughtSpecies, 1);
  assert.equal(codex.catchesToday, 1);
  assert.equal(codex.catchLimit, 5);
  assert.deepEqual(codex.constellations.map((c) => c.id), [Sky.todays(t, 'Asia/Seoul').id, Sky.todays(KST('2026-09-18T22:00:00'), 'Asia/Seoul').id]);
  assert.equal(codex.constellationsTotal, 365);
  await world.dispose();
  const sw = new World(getStudyRoom(), { now: () => t, store, tz: 'Asia/Seoul', npc: { autoStart: false }, study: { autoTick: false }, log: quiet, studyId: 7 });
  await sw.init();
  const q = sw.join({ nickname: '민수', socketId: 's2' }).player;
  assert.deepEqual(sw.tankInfo(), { available: false, fish: [], max: TANK_MAX });
  assert.equal((await sw.setTank(q, 'koi', true)).error, 'no_tank');
  await store.adjustCoins('민수', 100, 'test');
  const bought = await sw.purchase(q, 'shared_fish');
  assert.equal(bought.ok, true);
  const rel = await sw.releasePet(q, { inventoryId: bought.inventory.id, name: '물방울' });
  assert.equal(rel.ok, true);
  assert.equal(sw.tankInfo().available, true);
  assert.equal((await sw.setTank(q, 'carp', true)).error, 'not_caught');
  assert.equal((await sw.setTank(q, 'nope', true)).error, 'no_fish');
  const ok = await sw.setTank(q, 'koi', true);
  assert.equal(ok.ok, true);
  assert.deepEqual(ok.tank.map((f) => [f.fishId, f.by]), [['koi', '민수']]);
  assert.equal((await sw.setTank(q, 'koi', true)).error, 'already');
  const fishNpc = sw.tankPet().npc;
  assert.deepEqual(fishNpc.snapshot().tank, ['koi']);
  for (const id of ['carp', 'bass', 'trout']) await store.addFishCatch({ nickname: '민수', fishId: id }, t);
  await sw.setTank(q, 'carp', true);
  await sw.setTank(q, 'bass', true);
  assert.equal((await sw.setTank(q, 'trout', true)).error, 'tank_full');
  const other = sw.join({ nickname: '영희', socketId: 's3' }).player;
  assert.equal((await sw.setTank(other, 'koi', false)).error, 'forbidden');
  assert.equal((await sw.setTank(q, 'koi', false)).ok, true);
  assert.deepEqual(fishNpc.snapshot().tank, ['carp', 'bass']);
  assert.deepEqual((await store.roomPets(7)).find((r) => r.itemId === 'shared_fish').tank.map((f) => f.fishId), ['carp', 'bass']);
  const sw2 = new World(getStudyRoom(), { now: () => t, store, tz: 'Asia/Seoul', npc: { autoStart: false }, study: { autoTick: false }, log: quiet, studyId: 7 });
  await sw2.init();
  assert.deepEqual(sw2.tankPet().npc.tank.map((f) => f.fishId), ['carp', 'bass']);
  await sw.dispose();
  await sw2.dispose();
});

test('소켓 E2E 낚시·별자리·도감: fish:cast → playerFishing(wait → bite) → fish:reel → fish:caught + 채팅(희귀는 전체) · sky:view(밤/낮) · codex(어항 포함) · fish:tank(야외에서도 소속 스터디 어항 → 스터디 안 npc:update)', async (t) => {
  let clock = KST('2026-09-18T22:00:00');
  const srv = await boot({ world: { now: () => clock, npc: { autoStart: false, random: () => 0.999, tickMs: 150 }, study: { autoTick: false } } });
  t.after(() => srv.close());
  const a = connect(srv.port);
  const b = connect(srv.port);
  const c = connect(srv.port);
  t.after(() => { a.close(); b.close(); c.close(); });
  const ja = await joinAs(a, { nickname: '민수' });
  await joinAs(b, { nickname: '영희' });
  await joinAs(c, { nickname: '철수' });
  await srv.hub.store.adjustCoins('민수', 100, 'test');
  const bought = await ask(a, 'shop:buy', { itemId: 'shared_fish' });
  assert.equal((await ask(a, 'pet:release', { inventoryId: bought.inventory.id, name: '물방울' })).ok, true);
  const toOutdoor = async (s) => { s.emit('move', { x: 22.5 * T, y: 25 * T, facing: 'down', moving: false }); await sleep(30); const d = await ask(s, 'door', {}); assert.equal(d.ok, true); return d; };
  await toOutdoor(a);
  await toOutdoor(b);
  const out = srv.hub.outdoor;
  const pa = out.players.get(ja.self.id);
  const spot = out.room.interactables.find((i) => i.id === 'fish:1');
  pa.x = spot.x; pa.y = spot.y;
  const fishingB = collect(b, 'playerFishing');
  const chatsC = collect(c, 'chat');
  const chatsB = collect(b, 'chat');
  const cast = await ask(a, 'fish:cast', { id: 1 });
  assert.equal(cast.ok, true);
  await sleep(30);
  assert.deepEqual(fishingB[0].fishing, { state: 'wait', spot: '1' });
  clock = out.fishing.get(pa.id).biteAt + 50;
  out.tickFishing(clock);
  await sleep(30);
  assert.equal(fishingB[fishingB.length - 1].fishing.state, 'bite');
  const caught = once(b, 'fish:caught');
  const reel = await ask(a, 'fish:reel', {});
  assert.equal(reel.ok, true);
  assert.equal(reel.fish.id, 'golden_carp', 'random 0.999 → 희귀');
  assert.equal(reel.rare, true);
  const cg = await caught;
  assert.equal(cg.nickname, '민수');
  assert.equal(cg.fish.name, '황금 잉어');
  await sleep(50);
  assert.ok(chatsB.some((m) => m.system && /민수님이 황금 잉어을\(를\) 낚았어요/.test(m.text)));
  assert.ok(chatsC.some((m) => m.system && /희귀한 황금 잉어/.test(m.text)), '희귀는 스터디 안 사람에게도');
  assert.equal(fishingB[fishingB.length - 1].fishing, null);
  assert.equal(fishingB[fishingB.length - 1].result.ok, true);
  const tel = out.room.interactables.find((i) => i.id === 'telescope');
  pa.x = tel.x; pa.y = tel.y;
  const sky = await ask(a, 'sky:view', {});
  assert.equal(sky.ok, true);
  assert.equal(sky.constellation.name, Sky.todays(clock, 'Asia/Seoul').name);
  assert.equal(sky.first, true);
  clock = KST('2026-09-18T13:00:00');
  assert.equal((await ask(a, 'sky:view', {})).error, 'daytime');
  const codex = await ask(a, 'codex', {});
  assert.equal(codex.ok, true);
  assert.equal(codex.fish.find((f) => f.id === 'golden_carp').count, 1);
  assert.equal(codex.constellations.length, 1);
  assert.equal(codex.tank.available, true);
  const tank = await ask(a, 'fish:tank', { fishId: 'golden_carp', on: true });
  assert.equal(tank.ok, true);
  assert.deepEqual(tank.tank.map((f) => f.fishId), ['golden_carp']);
  assert.deepEqual((await ask(a, 'codex', {})).tank.fish.map((f) => f.fishId), ['golden_carp']);
  const upd = collect(c, 'npc:update');
  const study = srv.hub.worlds.get(srv.study.id);
  study.tankPet().npc.tick();
  await sleep(30);
  assert.ok(upd.some((u) => u.species === 'fish' && Array.isArray(u.tank) && u.tank.includes('golden_carp')));
  assert.equal((await ask(c, 'fish:cast', { id: 1 })).error, 'not_outdoor');
  assert.equal((await ask(b, 'fish:reel', {})).error, 'not_fishing');
});

let puppeteer = null;
try { puppeteer = require('puppeteer-core'); } catch (_) { /* devDependency 없음 */ }

test('브라우저 14단계 C: 낚시 자세(낚싯대·"!")·물고기 아이콘 · 별자리 오버레이(캔버스·이름·선 애니) · 낮 힌트 · 지갑 도감 탭(실루엣·잡은 종·별자리 기록)', { skip: !CHROME || !puppeteer ? 'Chrome/puppeteer-core 없음' : false, timeout: 180000 }, async (t) => {
  let clock = KST('2026-09-18T22:00:00');
  const srv = await boot({ world: { now: () => clock, npc: { autoStart: false, random: () => 0.5, tickMs: 150 }, study: { autoTick: false } } });
  t.after(() => srv.close());
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: CHROME_ARGS });
  t.after(() => browser.close());
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.stack || e.message));
  await page.setViewport({ width: 1200, height: 800 });
  await page.goto(`http://127.0.0.1:${srv.port}/?study=${srv.code}`, { waitUntil: 'networkidle0', timeout: 60000 });
  await page.waitForSelector('#login:not([hidden])', { timeout: 30000 });
  await page.type('#login-nick', '민수');
  await page.click('#login-submit');
  await page.waitForFunction(() => window.NSM && window.NSM.scene.me && document.getElementById('lobby').hidden, { timeout: 30000 });
  await page.evaluate(() => { window.NSM.net.move({ x: 22.5 * 32, y: 25 * 32, facing: 'down', moving: false }); });
  await sleep(60);
  await page.evaluate(() => window.NSM.net.door());
  await page.waitForFunction(() => window.NSM.net.room === 'outdoor' && window.NSM.scene.room.id === 'outdoor' && window.NSM.scene.me && window.NSM.scene.ready, { timeout: 30000 });
  await sleep(300);
  const out = srv.hub.outdoor;
  const me = out.players.get(await page.evaluate(() => window.NSM.scene.me.id));
  const spot = out.room.interactables.find((i) => i.id === 'fish:0');
  me.x = spot.x; me.y = spot.y;
  await page.evaluate((x, y) => { const s = window.NSM.scene; s.me.setPosition(x, y); s.lastSent = null; s.correction = null; }, spot.x, spot.y);
  await page.waitForFunction(() => !document.getElementById('sit-hint').hidden && /낚시하기/.test(document.getElementById('sit-hint').textContent), { timeout: 5000 });
  await page.keyboard.press('KeyE');
  await page.waitForFunction(() => window.NSM.scene.me.fishing && window.NSM.scene.me.fishing.state === 'wait' && window.NSM.scene.me.rod, { timeout: 5000 });
  await page.waitForFunction(() => /낚아채기/.test(document.getElementById('sit-hint').textContent), { timeout: 3000 });
  clock = out.fishing.get(me.id).biteAt + 50;
  out.tickFishing(clock);
  await page.waitForFunction(() => window.NSM.scene.me.fishing && window.NSM.scene.me.fishing.state === 'bite' && window.NSM.scene.me.bang, { timeout: 5000 });
  await page.keyboard.press('KeyE');
  await page.waitForFunction(() => !window.NSM.scene.me.fishing && window.NSM.scene.me.emojiText && /🐟|🐠|🐡/.test(window.NSM.scene.me.emojiText.text), { timeout: 5000 });
  const tel = out.room.interactables.find((i) => i.id === 'telescope');
  me.x = tel.x; me.y = tel.y;
  await page.evaluate(() => window.NSM.scene.hooks.onUse('telescope', 'telescope'));
  await page.waitForFunction(() => !document.getElementById('sky-modal').hidden, { timeout: 5000 });
  assert.equal(await page.$eval('#sky-name', (el) => el.textContent), Sky.todays(clock, 'Asia/Seoul').name);
  await page.waitForFunction(() => window.NSM.ui.skyDone === true, { timeout: 20000 });
  const canvasOk = await page.$eval('#sky-canvas', (cv) => { const d = cv.getContext('2d').getImageData(0, 0, cv.width, cv.height).data; let n = 0; for (let i = 3; i < d.length; i += 4) if (d[i] > 0) n++; return cv.width > 0 && n > 200; });
  assert.equal(canvasOk, true, '캔버스에 별이 그려졌다');
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.getElementById('sky-modal').hidden, { timeout: 3000 });
  clock = KST('2026-09-18T13:00:00');
  await page.evaluate(() => window.NSM.scene.hooks.onUse('telescope', 'telescope'));
  await page.waitForFunction(() => /밤\(19시~6시\)/.test(document.body.textContent), { timeout: 5000 });
  await page.evaluate(() => window.NSM.ui.openWallet('codex'));
  await page.waitForFunction(() => document.querySelectorAll('#wallet-items .codex-card').length === 10, { timeout: 8000 });
  const codex = await page.evaluate(() => ({ locked: document.querySelectorAll('#wallet-items .codex-card.locked').length, names: [...document.querySelectorAll('#wallet-items .codex-card .name')].map((n) => n.textContent), consts: document.querySelectorAll('#wallet-items .codex-const li').length, tab: [...document.querySelectorAll('#wallet-tabs button')].map((b) => b.textContent) }));
  assert.equal(codex.locked, 9);
  assert.equal(codex.names.filter((n) => n !== '???').length, 1);
  assert.equal(codex.consts, 1);
  assert.ok(codex.tab.includes('도감'));
  assert.deepEqual(errors, []);
});
